spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_schema
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test

  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true  # 색상 강조
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace